### ISSUE TITLE
Redirection de certains liens

### ISSUE THREAD

**Issue by RemyTrohel** [BryanNun/bookancien#3]
Certains liens font quitter le site au lieu d'ouvrir un autre onglet.

**Comment by wasthishelpful** [comment]
attention à n'ouvrir des onglets que si c'est justifié. quelques mauvaises raisons d'ouvrir un autre onglet quand on clique sur un lien :

https://css-tricks.com/use-target_blank/

il y a aussi des bonnes raisons dans la liste ;)
